//
//  CloudLogicAPIListViewController.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.8
//

import Foundation
import UIKit

class CloudLogicAPIListViewController: UITableViewController {
    
    private var cloudLogicAPIs: [CloudLogicAPI]?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        navigationItem.backBarButtonItem = UIBarButtonItem(title: "Back", style: .Plain, target: nil, action: nil)
        cloudLogicAPIs = CloudLogicAPIFactory.supportedCloudLogicAPIs
    }
    
    override func numberOfSectionsInTableView(tableView: UITableView) -> Int {
        guard let cloudLogicAPIs = cloudLogicAPIs else {return 0}
        return cloudLogicAPIs.count
    }
    
    override func tableView(tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 1
    }
    
    override func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCellWithIdentifier("CloudLogicAPITableCell", forIndexPath: indexPath) as! CloudLogicAPITableCell
        let cloudLogicAPI = cloudLogicAPIs![indexPath.section]
        cell.cloudLogicAPIName.text = cloudLogicAPI.displayName
        cell.cloudLogicAPIDescription.text = ""
        if let apiDescription = cloudLogicAPI.apiDescription {
            cell.cloudLogicAPIDescription.text = apiDescription
        }
        return cell
    }
    
    override func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
        tableView.deselectRowAtIndexPath(indexPath, animated: true)
        let showDetailsSegue = "CloudLogicAPIShowDetailsSegue"
        performSegueWithIdentifier(showDetailsSegue, sender: cloudLogicAPIs![indexPath.section])
    }
    
    override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
        if let destinationViewController = segue.destinationViewController as? CloudLogicAPIOperationsViewController {
            destinationViewController.cloudLogicAPI = sender as? CloudLogicAPI
        }
    }
}

class CloudLogicAPITableCell: UITableViewCell {
    @IBOutlet weak var cloudLogicAPIName: UILabel!
    @IBOutlet weak var cloudLogicAPIDescription: UILabel!
    
}
