//
//  CloudLogicAPIFactory.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.8
//

import Foundation
import AWSCore

class CloudLogicAPIFactory {
    static var supportedCloudLogicAPIs: [CloudLogicAPI] {
        
        return [
            CloudLogicAPI(displayName: "Refresh Statistics",
                apiDescription: "Refresh the popularity statistics and the status of various clubs",
                paths: [
                 "/refresh", "/refresh/123",                ],
                endPoint: "https://ix86ynyr95.execute-api.us-east-1.amazonaws.com/Development",
                apiClient: AWSAPI_IX86YNYR95_RefreshStatisticsMobileHubClient.init(forKey: AWSCloudLogicDefaultConfigurationKey)
            ),
        ]
    }
}
