//
//  NoSQLModelHelpers.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.8
//

import Foundation
import AWSDynamoDB

let GetItem = "GetItem"
let QueryWithPartitionKey = "QueryWithPartitionKey"
let QueryWithPartitionKeyAndFilter = "QueryWithPartitionKeyAndFilter"
let QueryWithPartitionKeyAndSortKey = "QueryWithPartitionKeyAndSortKey"
let QueryWithPartitionKeyAndSortKeyAndFilter = "QueryWithPartitionKeyAndSortKeyAndFilter"
let Scan = "Scan"
let ScanWithFilter = "ScanWithFilter"

@objc protocol Index {
    var indexName: String? {get}
    
    func supportedOperations() -> [String]
    
    optional func queryWithPartitionKeyDescription() -> String
    
    optional func queryWithPartitionKeyWithCompletionHandler(completionHandler: (response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void)
    
    optional func queryWithPartitionKeyAndFilterDescription() -> String
    
    optional func queryWithPartitionKeyAndFilterWithCompletionHandler(completionHandler: (response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void)
    
    optional func queryWithPartitionKeyAndSortKeyDescription() -> String
    
    optional func queryWithPartitionKeyAndSortKeyWithCompletionHandler(completionHandler: (response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void)
    
    optional func queryWithPartitionKeyAndSortKeyAndFilterDescription() -> String
    
    optional func queryWithPartitionKeyAndSortKeyAndFilterWithCompletionHandler(completionHandler: (response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void)
}
