//
//  ClubStatus.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.8
//

import Foundation
import UIKit
import AWSDynamoDB

class ClubStatus: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _club: String?
    var _nightOf: NSNumber?
    var _isOpen: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "streetstatus-mobilehub-663344442-club-status"
    }
    
    class func hashKeyAttribute() -> String {

        return "_club"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_nightOf"
    }
    
    override class func JSONKeyPathsByPropertyKey() -> [NSObject : AnyObject] {
        return [
               "_club" : "club",
               "_nightOf" : "night_of",
               "_isOpen" : "is_open",
               "_confidence" : "confidence"
        ]
    }
}
